### ISSUE TITLE
Hook silently fails

### ISSUE THREAD

**Issue by nictuku** [docteurklein/compose-ci#3]
Hi.

I followed the procedures and have the container running, with port 8321 exposed. When I try to trigger a build using curl, the HTTP request finishes but I get no output. I know I have some problems with my environment (certain source files are incomplete), but it's hard to make this work with no debugging information.

I tried to look at the container logs but I get nothing there either.

Would it be possible to print more logs on the HTTP server so we can see what happened with "docker logs" ?

Thank you!

**Comment by nictuku** [comment]
I'll make other notes here in case other users have problems.

Problem number one I had was that my `curl` was returning a 401 and I didn't know until I called it with -v:

```
* HTTP 1.0, assume close after body
< HTTP/1.0 401 Unauthorized
```

Perhaps we could add `-v` to the curl command suggestion on the README?

**Comment by docteurklein** [comment]
@nictuku hey there!
sorry for the delay, I didn't notice your issue before now.

The Readme is still very sparse, and it's definitely something to improve, but I can try to give you some hints.

## use `docker run -e LOG_LEVEL=DEBUG`

it will increase verbosity for everything, docker-compose included.

## pass the correct `GITHUB_TOKEN`

That's the reason why you get a 401. If curl returns no output, there is a problem for sure.  
I will add the `-v` option to curl as you proposed. good idea :)

## use `-e GARBAGE_COLLECT=0`

it will keep all the containers created, in order to help you see what happened afterwards.

## look at the logs of the build container

The `uuid` displayed by curl is the name of the container running the build.  
You can see what happens by doing:

```
docker logs --tail <uuid>
```

Hope it helps!
Don't hesitate to continue this thread with all the problems you encountered. 
The project is very young and buggy, so any help or comment is appreciated :)

**Comment by nictuku** [comment]
I'm still stuck. The POST request still returns a 401. Yes I understand the likely cause being an incorrect token, but it would be nice if compose-ci logged the error that it's getting from github. Otherwise it's a game of guessing :-P.

The container isn't logging anything even after I'm using -e LOG_LEVEL=DEBUG

**Comment by docteurklein** [comment]
yeah, logging happens only **after** the build is accepted (non 401).
I will add logs for this part too.

**Comment by docteurklein** [comment]
@nictuku I just added a PR for that. you can try it by using the image tagged: 

```
docteurklein/compose-ci:feature_logs
```
